export const avatars = {
  Jude: "https://api.dicebear.com/9.x/adventurer/svg?seed=Jude",
  Chase: "https://api.dicebear.com/9.x/adventurer-neutral/svg?seed=Chase",
  Kimberly: "https://api.dicebear.com/9.x/avataaars/svg?seed=Kimberly",
  Mason: "https://api.dicebear.com/9.x/bottts/svg?seed=Mason",
  Jameson: "https://api.dicebear.com/9.x/bottts/svg?seed=Jameson",
  Maria: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Maria",
  George: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=George",
  Christian: "https://api.dicebear.com/9.x/dylan/svg?seed=Christian",
  Eden: "https://api.dicebear.com/9.x/miniavs/svg?seed=Eden",
  Sadie: "https://api.dicebear.com/9.x/miniavs/svg?seed=Sadie",
  Ryan: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Ryan",
  Katherine: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Katherine",
  Brian: "https://api.dicebear.com/9.x/bottts/svg?seed=Brian",
  Liam: "https://api.dicebear.com/9.x/bottts/svg?seed=Liam",
};
